# Question 1

Tasks:
Load the Iris dataset (csv file present in the classroom).


Choose one random sample from each class (Setosa, Versicolor, and Virginica) which will act as the test data.


Compute the mean vector and covariance matrix for each class (without the sample picked in the previous part, now it will act as the test data).


Calculate the Mahalanobis distance for each of the selected samples with each of the class using the formula:
Mahalanobis distance = sqrt((x - μ)ᵀ * Σ⁻¹ * (x - μ))
Where:
x is the feature vector of the sample.
μ is the mean vector of the entire dataset.
Σ⁻¹ is the inverse of the covariance matrix.

Compare the Mahalanobis distances for the three samples and classify each sample to the class with the smallest Mahalanobis distance.




In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


### Load the Iris dataset (csv file present in the classroom).

In [3]:
path = "/content/drive/MyDrive/PRML/LAB_3/iris.csv"
df = pd.read_csv(path)

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None


### Choose one random sample from each class (Setosa, Versicolor, and Virginica) which will act as the test data.

In [5]:
test = pd.DataFrame()
for ind,row in df.iterrows():
  if (ind == 21) or (ind == 86) or (ind == 129):
    #predict_test_case = pd.concat([predict_test_case, new_row], ignore_index=True)
    #new_row = pd.DataFrame({'Id' : [rows.Id], 'Distance' : [Dist], 'Species':[rows.Species]})
    new_row = pd.DataFrame({'Id': [row.Id], 'SepalLengthCm': [row.SepalLengthCm], 'SepalWidthCm': [row.SepalWidthCm], 'PetalLengthCm' :[row.PetalLengthCm], 'PetalWidthCm' : [row.PetalWidthCm], 'Species' : [row.Species]})
    test = pd.concat([test,new_row], ignore_index = True)
    df.drop(df[df['Id'] == ind].index, inplace = True)

print(test)
print(df.info())


    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   22            5.1           3.7            1.5           0.4   
1   87            6.7           3.1            4.7           1.5   
2  130            7.2           3.0            5.8           1.6   

           Species  
0      Iris-setosa  
1  Iris-versicolor  
2   Iris-virginica  
<class 'pandas.core.frame.DataFrame'>
Int64Index: 147 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             147 non-null    int64  
 1   SepalLengthCm  147 non-null    float64
 2   SepalWidthCm   147 non-null    float64
 3   PetalLengthCm  147 non-null    float64
 4   PetalWidthCm   147 non-null    float64
 5   Species        147 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 8.0+ KB
None


### Compute the mean vector and covariance matrix for each class

In [6]:
mean_vector = []

counter_1 = 0
counter_2 = 0
counter_3 =0

sepal_length_c_1 = 0
sepal_width_c_1 = 0
petal_length_c_1 = 0
petal_width_c_1 = 0

sepal_length_c_2 = 0
sepal_width_c_2 = 0
petal_length_c_2 = 0
petal_width_c_2 = 0

sepal_length_c_3 = 0
sepal_width_c_3 = 0
petal_length_c_3 = 0
petal_width_c_3 = 0

for ind,row in df.iterrows():
  if row.Species == 'Iris-setosa':
    counter_1 = counter_1 + 1
    sepal_length_c_1 = sepal_length_c_1 + row.SepalLengthCm
    sepal_width_c_1 = sepal_width_c_1 + row.SepalWidthCm
    petal_length_c_1 = petal_length_c_1 + row.PetalLengthCm
    petal_width_c_1 = petal_width_c_1 + row.PetalWidthCm
  elif row.Species == 'Iris-versicolor':
    counter_2 = counter_2 + 1
    sepal_length_c_2 = sepal_length_c_2 + row.SepalLengthCm
    sepal_width_c_2 = sepal_width_c_2 + row.SepalWidthCm
    petal_length_c_2 = petal_length_c_2 + row.PetalLengthCm
    petal_width_c_2 = petal_width_c_2 + row.PetalWidthCm
  elif row.Species == 'Iris-virginica':
    counter_3 = counter_3 + 1
    sepal_length_c_3 = sepal_length_c_3 + row.SepalLengthCm
    sepal_width_c_3 = sepal_width_c_3 + row.SepalWidthCm
    petal_length_c_3 = petal_length_c_3 + row.PetalLengthCm
    petal_width_c_3 = petal_width_c_3 + row.PetalWidthCm


mean_sepal_length_1 = sepal_length_c_1/counter_1
mean_sepal_width_1 = sepal_width_c_1/counter_1
mean_petal_length_1 = petal_length_c_1/counter_1
mean_petal_width_1 = petal_width_c_1/counter_1

mean_vector_1 = np.array([mean_sepal_length_1, mean_sepal_width_1, mean_petal_length_1, mean_petal_width_1])

mean_sepal_length_2 = sepal_length_c_2/counter_2
mean_sepal_width_2 = sepal_width_c_2/counter_2
mean_petal_length_2 = petal_length_c_2/counter_2
mean_petal_width_2 = petal_width_c_2/counter_2

mean_vector_2 = np.array([mean_sepal_length_2, mean_sepal_width_2, mean_petal_length_2, mean_petal_width_2])

mean_sepal_length_3 = sepal_length_c_3/counter_3
mean_sepal_width_3 = sepal_width_c_3/counter_3
mean_petal_length_3 = petal_length_c_3/counter_3
mean_petal_width_3 = petal_width_c_3/counter_3

mean_vector_3 = np.array([mean_sepal_length_3, mean_sepal_width_3, mean_petal_length_3, mean_petal_width_3])

In [7]:
cov_matr =[]
#subtract the mean, square and add
#var(x)   cov(x,y)    cov(x,z)  cov(x,u)
#cov(y,x) var(y)      cov(y,z)  cov(y,u)
#cov(z,x)  cov(z,y)   var(z)    cov(z,u)
#cov(u,x)  cov(u,y)   cov(u,z)  var(u)

#x = sepal length
#y = sepal width
#z = petal length
#u = petal width

#for cov youre basically multiplying the diff with each other
#square with itself
#var(x) for Iris-setosa x = sepal length
counter_c1 = 0
counter_c2 = 0
counter_c3 = 0
sepal_length_var_c_1 = 0
sepal_width_var_c_1 = 0
petal_width_var_c_1 = 0
petal_length_var_c_1 = 0

sepal_len_petal_len_c_1 = 0
sepal_len_petal_wid_c_1 = 0
sepal_len_sepal_wid_c_1 = 0
petal_len_petal_wid_c_1 = 0

sepal_wid_petal_len_c_1 = 0
sepal_wid_petal_wid_c_1 = 0


sepal_length_var_c_2 = 0
sepal_width_var_c_2 = 0
petal_width_var_c_2 = 0
petal_length_var_c_2 = 0

sepal_len_petal_len_c_2 = 0
sepal_len_petal_wid_c_2 = 0
sepal_len_sepal_wid_c_2 = 0
petal_len_petal_wid_c_2 = 0

sepal_wid_petal_len_c_2 = 0
sepal_wid_petal_wid_c_2 = 0


sepal_length_var_c_3 = 0
sepal_width_var_c_3 = 0
petal_width_var_c_3 = 0
petal_length_var_c_3 = 0

sepal_len_petal_len_c_3 = 0
sepal_len_petal_wid_c_3 = 0
sepal_len_sepal_wid_c_3 = 0
petal_len_petal_wid_c_3 = 0

sepal_wid_petal_len_c_3 = 0
sepal_wid_petal_wid_c_3 = 0

for ind,row in df.iterrows():
  if row.Species == 'Iris-setosa':
    counter_c1 = counter_c1 + 1
    sepal_length_var_c_1 = sepal_length_var_c_1 + (row.SepalLengthCm - mean_vector_1[0])**2
    sepal_width_var_c_1 =sepal_width_var_c_1 + (row.SepalWidthCm - mean_vector_1[1])**2
    petal_length_var_c_1 =petal_length_var_c_1 + (row.PetalLengthCm - mean_vector_1[2])**2
    petal_width_var_c_1 = petal_width_var_c_1 + (row.PetalWidthCm - mean_vector_1[3])**2

    sepal_len_petal_len_c_1 = sepal_len_petal_len_c_1 + ((row.SepalLengthCm - mean_vector_1[0])*(row.PetalLengthCm - mean_vector_1[2]))
    sepal_len_petal_wid_c_1 = sepal_len_petal_wid_c_1 + ((row.SepalLengthCm - mean_vector_1[0])*(row.PetalWidthCm - mean_vector_1[3]))
    sepal_len_sepal_wid_c_1 = sepal_len_sepal_wid_c_1 + ((row.SepalLengthCm - mean_vector_1[0])*(row.SepalWidthCm - mean_vector_1[1]))
    petal_len_petal_wid_c_1 = petal_len_petal_wid_c_1 + ((row.PetalLengthCm - mean_vector_1[2])*(row.PetalWidthCm - mean_vector_1[3]))

    sepal_wid_petal_len_c_1 = sepal_wid_petal_len_c_1 + ((row.SepalWidthCm - mean_vector_1[1])*(row.PetalLengthCm - mean_vector_1[2]))
    sepal_wid_petal_wid_c_1 = sepal_wid_petal_wid_c_1 + ((row.SepalWidthCm - mean_vector_1[1])*(row.PetalWidthCm - mean_vector_1[3]))

  elif row.Species == 'Iris-versicolor':
    counter_c2 = counter_c2 + 1
    sepal_length_var_c_2 = sepal_length_var_c_2 + (row.SepalLengthCm - mean_vector_2[0])**2
    sepal_width_var_c_2 =sepal_width_var_c_2 + (row.SepalWidthCm - mean_vector_2[1])**2
    petal_length_var_c_2 =petal_length_var_c_2 + (row.PetalLengthCm - mean_vector_2[2])**2
    petal_width_var_c_2 = petal_width_var_c_2 + (row.PetalWidthCm - mean_vector_2[3])**2

    sepal_len_petal_len_c_2 = sepal_len_petal_len_c_2 + ((row.SepalLengthCm - mean_vector_2[0])*(row.PetalLengthCm - mean_vector_2[2]))
    sepal_len_petal_wid_c_2 = sepal_len_petal_wid_c_2 + ((row.SepalLengthCm - mean_vector_2[0])*(row.PetalWidthCm - mean_vector_2[3]))
    sepal_len_sepal_wid_c_2 = sepal_len_sepal_wid_c_2 + ((row.SepalLengthCm - mean_vector_2[0])*(row.SepalWidthCm - mean_vector_2[1]))
    petal_len_petal_wid_c_2 = petal_len_petal_wid_c_2 + ((row.PetalLengthCm - mean_vector_2[2])*(row.PetalWidthCm - mean_vector_2[3]))

    sepal_wid_petal_len_c_2 = sepal_wid_petal_len_c_2 + ((row.SepalWidthCm - mean_vector_2[1])*(row.PetalLengthCm - mean_vector_2[2]))
    sepal_wid_petal_wid_c_2 = sepal_wid_petal_wid_c_2 + ((row.SepalWidthCm - mean_vector_2[1])*(row.PetalWidthCm - mean_vector_2[3]))

  elif row.Species == 'Iris-virginica':
    counter_c3 = counter_c3 + 1
    sepal_length_var_c_3 = sepal_length_var_c_3 + (row.SepalLengthCm - mean_vector_3[0])**2
    sepal_width_var_c_3 =sepal_width_var_c_3 + (row.SepalWidthCm - mean_vector_3[1])**2
    petal_length_var_c_3 =petal_length_var_c_3 + (row.PetalLengthCm - mean_vector_3[2])**2
    petal_width_var_c_3 = petal_width_var_c_3 + (row.PetalWidthCm - mean_vector_3[3])**2

    sepal_len_petal_len_c_3 = sepal_len_petal_len_c_3 + ((row.SepalLengthCm - mean_vector_3[0])*(row.PetalLengthCm - mean_vector_3[2]))
    sepal_len_petal_wid_c_3 = sepal_len_petal_wid_c_3 + ((row.SepalLengthCm - mean_vector_3[0])*(row.PetalWidthCm - mean_vector_3[3]))
    sepal_len_sepal_wid_c_3 = sepal_len_sepal_wid_c_3 + ((row.SepalLengthCm - mean_vector_3[0])*(row.SepalWidthCm - mean_vector_3[1]))
    petal_len_petal_wid_c_3 = petal_len_petal_wid_c_3 + ((row.PetalLengthCm - mean_vector_3[2])*(row.PetalWidthCm - mean_vector_3[3]))

    sepal_wid_petal_len_c_3 = sepal_wid_petal_len_c_3 + ((row.SepalWidthCm - mean_vector_3[1])*(row.PetalLengthCm - mean_vector_3[2]))
    sepal_wid_petal_wid_c_3 = sepal_wid_petal_wid_c_3 + ((row.SepalWidthCm - mean_vector_3[1])*(row.PetalWidthCm - mean_vector_3[3]))


cov_mat_1 = np.matrix([[sepal_length_var_c_1, sepal_len_sepal_wid_c_1, sepal_len_petal_len_c_1, sepal_len_petal_wid_c_1],
             [sepal_len_sepal_wid_c_1, sepal_width_var_c_1, sepal_wid_petal_len_c_1, sepal_wid_petal_wid_c_1],
             [sepal_len_petal_len_c_1, sepal_wid_petal_len_c_1, petal_length_var_c_1, petal_len_petal_wid_c_1],
             [sepal_len_petal_wid_c_1, sepal_wid_petal_wid_c_1, petal_len_petal_wid_c_1, petal_width_var_c_1]])

cov_mat_2 = np.matrix([[sepal_length_var_c_2, sepal_len_sepal_wid_c_2, sepal_len_petal_len_c_2, sepal_len_petal_wid_c_2],
             [sepal_len_sepal_wid_c_2, sepal_width_var_c_2, sepal_wid_petal_len_c_2, sepal_wid_petal_wid_c_2],
             [sepal_len_petal_len_c_2, sepal_wid_petal_len_c_2, petal_length_var_c_2, petal_len_petal_wid_c_2],
             [sepal_len_petal_wid_c_2, sepal_wid_petal_wid_c_2, petal_len_petal_wid_c_2, petal_width_var_c_2]])

cov_mat_3 = np.matrix([[sepal_length_var_c_3, sepal_len_sepal_wid_c_3, sepal_len_petal_len_c_3, sepal_len_petal_wid_c_3],
             [sepal_len_sepal_wid_c_3, sepal_width_var_c_3, sepal_wid_petal_len_c_3, sepal_wid_petal_wid_c_3],
             [sepal_len_petal_len_c_3, sepal_wid_petal_len_c_3, petal_length_var_c_3, petal_len_petal_wid_c_3],
             [sepal_len_petal_wid_c_3, sepal_wid_petal_wid_c_3, petal_len_petal_wid_c_3, petal_width_var_c_3]])


In [10]:
print("Covariance matrix is of the form : \n")
print("var(x)   cov(x,y)    cov(x,z)  cov(x,u)")
print("cov(y,x) var(y)      cov(y,z)  cov(y,u)")
print("cov(z,x)  cov(z,y)   var(z)    cov(z,u)")
print("cov(u,x)  cov(u,y)   cov(u,z)  var(u)")
print("\nx = sepal length\ny = sepal width\nz = petal length\nu = petal width\n\n")
print()
print()
print("Mean Vector for Class A~Iris-setosa : ")
print(mean_vector_1)
print()
print("Covariance matrix for Class A-Iris setosa : ")
print(cov_mat_1)
print()
print()
print("Mean Vector for Class B~Iris-versicolor : ")
print(mean_vector_2)
print()
print("Covariance matrix for Class B-Iris setosa : ")
print(cov_mat_2)
print()
print()
print("Mean Vector for Class C~Iris-virginica : ")
print(mean_vector_3)
print()
print("Covariance matrix for Class C-Iris setosa : ")
print(cov_mat_3)
print()

Covariance matrix is of the form : 

var(x)   cov(x,y)    cov(x,z)  cov(x,u)
cov(y,x) var(y)      cov(y,z)  cov(y,u)
cov(z,x)  cov(z,y)   var(z)    cov(z,u)
cov(u,x)  cov(u,y)   cov(u,z)  var(u)

x = sepal length
y = sepal width
z = petal length
u = petal width




Mean Vector for Class A~Iris-setosa : 
[4.99795918 3.41836735 1.45918367 0.24489796]

Covariance matrix for Class A-Iris setosa : 
[[5.92979592 4.92183673 0.69591837 0.5344898 ]
 [4.92183673 7.11346939 0.57673469 0.55959184]
 [0.69591837 0.57673469 1.41836735 0.28979592]
 [0.5344898  0.55959184 0.28979592 0.56122449]]


Mean Vector for Class B~Iris-versicolor : 
[5.93469388 2.75714286 4.25510204 1.32040816]

Covariance matrix for Class B-Iris setosa : 
[[13.05102041  4.13285714  8.94632653  2.71530612]
 [ 4.13285714  4.42        3.89571429  1.84285714]
 [ 8.94632653  3.89571429 10.76122449  3.51489796]
 [ 2.71530612  1.84285714  3.51489796  1.83959184]]


Mean Vector for Class C~Iris-virginica : 
[6.59183673 2.97755102 5.551

### Calculate the Mahalanobis distance for each of the selected samples with each of the class using the formula:

Mahalanobis distance = sqrt((x - μ)ᵀ * Σ⁻¹ * (x - μ))

Where:

x is the feature vector of the sample.

μ is the mean vector for each class.

Σ⁻¹ is the inverse of the covariance matrix for each class.


In [11]:
#for test case
print(test)

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   22            5.1           3.7            1.5           0.4   
1   87            6.7           3.1            4.7           1.5   
2  130            7.2           3.0            5.8           1.6   

           Species  
0      Iris-setosa  
1  Iris-versicolor  
2   Iris-virginica  


In [12]:
#test_case_1

#cass A = Iris-setosa
#case B = Iris-versicolor
#case C = Iris-virginica

#mean vectors:
#mean_vector_1
#mean_vector_2
#mean_vector_3

test_case_1 = test.iloc[[0]]
print(test_case_1)


test_x_1 = np.array([test_case_1.SepalLengthCm, test_case_1.SepalWidthCm, test_case_1.PetalLengthCm, test_case_1.PetalWidthCm])

#mahalnobis_dist = np.sqrt(((x - μ)ᵀ * Σ⁻¹ * (x - μ)))
#for class one Iris-setosa:
mahalnobis_dist_1_A = np.sqrt((test_x_1.reshape(1,4) - mean_vector_1)*(np.linalg.inv(cov_mat_1))*(test_x_1 - mean_vector_1.reshape(4,1)))
print("Mahalnobis distance for sample 1 and class A~Iris-setosa")
print(mahalnobis_dist_1_A)

#for class two Iris-versicolor:
mahalnobis_dist_1_B = np.sqrt((test_x_1.reshape(1,4) - mean_vector_2)*(np.linalg.inv(cov_mat_2))*(test_x_1 - mean_vector_2.reshape(4,1)))
print("\nMahalnobis distance for sample 1 and class B~Iris-versicolor")
print(mahalnobis_dist_1_B)

#for class three Iris-virginica:
mahalnobis_dist_1_C = np.sqrt((test_x_1.reshape(1,4) - mean_vector_3)*(np.linalg.inv(cov_mat_3))*(test_x_1 - mean_vector_3.reshape(4,1)))
print("\nMahalnobis distance for sample 1 and class C~Iris-virginica")
print(mahalnobis_dist_1_C)

print("\n\nPredicted class is : Iris-setosa")
print("Original class is : ", test_case_1.Species[0])


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0  22            5.1           3.7            1.5           0.4  Iris-setosa
Mahalnobis distance for sample 1 and class A~Iris-setosa
[[0.23039015]]

Mahalnobis distance for sample 1 and class B~Iris-versicolor
[[1.51393904]]

Mahalnobis distance for sample 1 and class C~Iris-virginica
[[1.89984568]]


Predicted class is : Iris-setosa
Original class is :  Iris-setosa


In [13]:
#test_case_2

#cass A = Iris-setosa
#case B = Iris-versicolor
#case C = Iris-virginica

#mean vectors:
#mean_vector_1
#mean_vector_2
#mean_vector_3

test_case_2 = test.iloc[[1]]
print(test_case_2)


test_x_2 = np.array([test_case_2.SepalLengthCm, test_case_2.SepalWidthCm, test_case_2.PetalLengthCm, test_case_2.PetalWidthCm])

#mahalnobis_dist = np.sqrt(((x - μ)ᵀ * Σ⁻¹ * (x - μ)))
#for class one Iris-setosa:
mahalnobis_dist_2_A = np.sqrt((test_x_2.reshape(1,4) - mean_vector_1)*(np.linalg.inv(cov_mat_1))*(test_x_2 - mean_vector_1.reshape(4,1)))
print("Mahalnobis distance for sample 2 and class A~Iris-setosa")
print(mahalnobis_dist_2_A)

#for class two Iris-versicolor:
mahalnobis_dist_2_B = np.sqrt((test_x_2.reshape(1,4) - mean_vector_2)*(np.linalg.inv(cov_mat_2))*(test_x_2 - mean_vector_2.reshape(4,1)))
print("\nMahalnobis distance for sample 2 and class B~Iris-versicolor")
print(mahalnobis_dist_2_B)

#for class three Iris-virginica:
mahalnobis_dist_2_C = np.sqrt((test_x_2.reshape(1,4) - mean_vector_3)*(np.linalg.inv(cov_mat_3))*(test_x_2 - mean_vector_3.reshape(4,1)))
print("\nMahalnobis distance for sample 2 and class C~Iris-virginica")
print(mahalnobis_dist_2_C)


print("\n\nPredicted class is : Iris-versicolor")
print("Original class is : ", test_case_2.Species[1])


   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
1  87            6.7           3.1            4.7           1.5   

           Species  
1  Iris-versicolor  
Mahalnobis distance for sample 2 and class A~Iris-setosa
[[3.04912208]]

Mahalnobis distance for sample 2 and class B~Iris-versicolor
[[0.22845941]]

Mahalnobis distance for sample 2 and class C~Iris-virginica
[[0.56194455]]


Predicted class is : Iris-versicolor
Original class is :  Iris-versicolor


In [14]:
#test_case_2

#cass A = Iris-setosa
#case B = Iris-versicolor
#case C = Iris-virginica

#mean vectors:
#mean_vector_1
#mean_vector_2
#mean_vector_3

test_case_3 = test.iloc[[2]]
print(test_case_3)


test_x_3 = np.array([test_case_3.SepalLengthCm, test_case_3.SepalWidthCm, test_case_3.PetalLengthCm, test_case_3.PetalWidthCm])

#mahalnobis_dist = np.sqrt(((x - μ)ᵀ * Σ⁻¹ * (x - μ)))
#for class one Iris-setosa:
mahalnobis_dist_3_A = np.sqrt((test_x_3.reshape(1,4) - mean_vector_1)*(np.linalg.inv(cov_mat_1))*(test_x_3 - mean_vector_1.reshape(4,1)))
print("Mahalnobis distance for sample 3 and class A~Iris-setosa")
print(mahalnobis_dist_3_A)

#for class two Iris-versicolor:
mahalnobis_dist_3_B = np.sqrt((test_x_3.reshape(1,4) - mean_vector_2)*(np.linalg.inv(cov_mat_2))*(test_x_3 - mean_vector_2.reshape(4,1)))
print("\nMahalnobis distance for sample 3 and class B~Iris-versicolor")
print(mahalnobis_dist_3_B)

#for class three Iris-virginica:
mahalnobis_dist_3_C = np.sqrt((test_x_3.reshape(1,4) - mean_vector_3)*(np.linalg.inv(cov_mat_3))*(test_x_3 - mean_vector_3.reshape(4,1)))
print("\nMahalnobis distance for sample 3 and class C~Iris-virginica")
print(mahalnobis_dist_3_C)


print("\n\nPredicted class is : Iris-virginica")
print("Original class is : ", test_case_3.Species[2])

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
2  130            7.2           3.0            5.8           1.6   

          Species  
2  Iris-virginica  
Mahalnobis distance for sample 3 and class A~Iris-setosa
[[3.94831937]]

Mahalnobis distance for sample 3 and class B~Iris-versicolor
[[0.54948726]]

Mahalnobis distance for sample 3 and class C~Iris-virginica
[[0.32010813]]


Predicted class is : Iris-virginica
Original class is :  Iris-virginica
